[package]
name = "greprs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = "1.0"
rayon = "1.0"
tempfile = "3.0"
glob = "0.3"
atty = "0.2"
memmap2 = "0.9"

[dev-dependencies]
tempfile = "3.0"
